spring.application.name=mobile-bff

server.port=8080

logging.level.root=info
logging.level.com.project.mobilebfflab=debug

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
