spring.application.name=mobile-bff

server.port=8080

logging.level.root=info
logging.level.com.project.mobilebfflab=debug

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# === Resilience4j CircuitBreaker ===
resilience4j.circuitbreaker.instances.userService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.accountsService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountsService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.accountsService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.accountsService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.accountsService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.accountsService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.accountsService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.offersService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.offersService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.offersService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.offersService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.offersService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.offersService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.offersService.permittedNumberOfCallsInHalfOpenState=3
